batch_size: 1
cfg_path: /project/config.yaml
colormode: 'RGB'
data:
  covering: true
  gaussian_noise: 12.75
  hist_eq: true
  motion_blur: true
  normalize_images: true
  rotation: 30
  scale_jitter:
  - 0.5
  - 1.25
  translation: 40
device: cuda:0
display_iters: 50
epochs: 200
model:
  backbone:
    pretrained: https://download.pytorch.org/models/resnet50-19c8e357.pth
    type: ResNet
  pose_model:
    stride: 8
optimizer:
  params:
    lr: 0.0001
  type: AdamW
save_epochs: 50
scheduler:
  params:
    lr_list:
    - - 0.00001
    - - 0.000001
    milestones:
    - 90
    - 120
  type: LRListScheduler
seed: 42
runner:
  type: PoseRunner
with_center: false
