model:
  backbone:
    type: ResNet
    model_name: resnet50
    pretrained: true
  backbone_output_channels: 2048
optimizer:
  type: AdamW
  params:
    lr: 0.001
scheduler:
  type: LRListScheduler
  params:
    lr_list:
    - - 0.0001
    - - 0.00001
    milestones:
    - 90
    - 120