model:
  backbone:
    type: ResNet
    model_name: resnet101
    pretrained: true
  backbone_output_channels: 2048
runner:
  optimizer:
    type: AdamW
    params:
      lr: 0.001
  scheduler:
    type: LRListScheduler
    params:
      lr_list: [ [ 1e-4 ], [ 1e-5 ] ]
      milestones: [ 160, 190 ]