batch_size: 1
cfg_path:
colormode: RGB
data:
  covering: true
  gaussian_noise: 12.75
  hist_eq: true
  motion_blur: true
  normalize_images: true
  rotation: 30
  scale_jitter:
  - 0.5
  - 1.25
device: cuda
display_iters: 50
epochs: 200
optimizer:
  type: AdamW
  params:
    lr: 0.0001
runner:
  type: PoseRunner
save_epochs: 50
scheduler:
  type: LRListScheduler
  params:
    lr_list:
    - - 0.00001
    - - 0.000001
    milestones:
    - 90
    - 120
seed: 42
method: bu
